name: roslib
description: Interface with a ROS node over websockets with rosbridge, heavily influenced by roslibjs and follows the same structure.
version: 0.0.3
homepage: https://github.com/eternali/roslib

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  web_socket_channel: ^2.1.0

dev_dependencies:
  test: ^1.19.5
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
